# Site settings
title: gslnmr
description: A simple site with custom layouts
url: https://geiselnehmer.de
baseurl: "" # Leave empty unless hosted in a subdirectory

# Author information
author:
  name: ptrsmd

# Plugins
plugins:
  - jekyll-seo-tag # Optional: Adds SEO-friendly metadata

# Markdown settings
markdown: kramdown

# Exclude files from build
exclude:
  - README.md
